/* GENERATED by build/emit-css.mjs from src/tokens.json. Do not edit.
   Imported by src/email.js. Flat literals, no custom properties: mail clients strip them. */
/* Roles, and the token each reads:
 *   page     --color-bg              the page behind the card, and the footer's ground
 *   card     --color-bg-card         the card
 *   border   --color-border          the card's hairline
 *   rule     --color-border-light    a divider inside the card
 *   heading  --color-text            the heading, a quoted title, the text wordmark
 *   text     --color-text-secondary  body copy
 *   muted    --color-text-muted      notes, the fallback link's label, the footer
 *   link     --color-link-text       link text: the gradient's dark stop in light, yellow in dark
 *   buttonBg --color-link-text       the button's fill
 *   buttonFg --color-primary-fg      the button's label
 *   quoteBg  --color-bg              a quoted title's panel
 *   quoteBar --color-link            a quoted title's edge
 */
export const palette = {
  "label": "NFC.cool",
  "font": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "radius": {
    "card": "14px",
    "button": "10px"
  },
  "light": {
    "page": "#F5F6F8",
    "card": "#FFFFFF",
    "border": "#E6E8EB",
    "rule": "#F0F1F3",
    "heading": "#212529",
    "text": "#495057",
    "muted": "#666D74",
    "link": "#1A60CE",
    "buttonBg": "#1A60CE",
    "buttonFg": "#FFFFFF",
    "quoteBg": "#F5F6F8",
    "quoteBar": "#128CF0"
  },
  "dark": {
    "page": "#161B22",
    "card": "#1C2128",
    "border": "#30363D",
    "rule": "#21262D",
    "heading": "#F0F2F5",
    "text": "#C2C8D0",
    "muted": "#8B949E",
    "link": "#FFC700",
    "buttonBg": "#FFC700",
    "buttonFg": "#161B22",
    "quoteBg": "#161B22",
    "quoteBar": "#FFC700"
  }
};
